MESSAGE(STATUS "+++ FindParse.cmake")
SET (THIRD_DIR_ROOT ${PROJECT_SOURCE_DIR}/third)
SET (CJSONOBJECT_DIR_ROOT ${PROJECT_SOURCE_DIR}/third/cjsonObject)
SET (CORE_DIR_ROOT ${PROJECT_SOURCE_DIR}/core/Parse)
SET (CORE_JSON_DIR_ROOT ${PROJECT_SOURCE_DIR}/core/Parse/json)


if(NOT EXISTS ${CORE_JSON_DIR_ROOT})
	EXECUTE_PROCESS(COMMAND mkdir -p ${CORE_JSON_DIR_ROOT}
									WORKING_DIRECTORY ${CORE_DIR_ROOT})
endif()
if(NOT EXISTS ${CJSONOBJECT_DIR_ROOT})
	EXECUTE_PROCESS(COMMAND mkdir -p ${CJSONOBJECT_DIR_ROOT}
									WORKING_DIRECTORY ${THIRD_DIR_ROOT})
endif()



#克隆CJSON
FUNCTION (CLONE_PARSE_CJSON)
	MESSAGE(STATUS "+++ BUILD_JSONCPP")
	#Setp 1 克隆hipe工程
	EXECUTE_PROCESS ( COMMAND git clone https://github.com/Bwar/CJsonObject.git ${CJSONOBJECT_DIR_ROOT}
										WORKING_DIRECTORY ${CJSONOBJECT_DIR_ROOT})

	MESSAGE(STATUS "--- BUILD_JSONCPP")
ENDFUNCTION ()



if(NOT EXISTS ${CJSONOBJECT_DIR_ROOT}/cJSON.h)
	CLONE_PARSE_CJSON()
endif()
if(NOT EXISTS ${CORE_JSON_DIR_ROOT}/cJSON.h)
	EXECUTE_PROCESS ( COMMAND cp ${CJSONOBJECT_DIR_ROOT}/cJSON.h ${CORE_JSON_DIR_ROOT}
	WORKING_DIRECTORY ${CJSONOBJECT_DIR_ROOT})   
	EXECUTE_PROCESS ( COMMAND cp ${CJSONOBJECT_DIR_ROOT}/cJSON.c ${CORE_JSON_DIR_ROOT}
	WORKING_DIRECTORY ${CJSONOBJECT_DIR_ROOT})   
	EXECUTE_PROCESS ( COMMAND cp ${CJSONOBJECT_DIR_ROOT}/CJsonObject.cpp ${CORE_JSON_DIR_ROOT}
	WORKING_DIRECTORY ${CJSONOBJECT_DIR_ROOT})   
	EXECUTE_PROCESS ( COMMAND cp ${CJSONOBJECT_DIR_ROOT}/CJsonObject.hpp ${CORE_JSON_DIR_ROOT}
	WORKING_DIRECTORY ${CJSONOBJECT_DIR_ROOT})   
endif()



MESSAGE("HAHAHAHAHAHAHAHAHAHA" ${CJSONOBJECT_DIR_ROOT})
set (PARSE_FOUND TRUE)

MESSAGE(STATUS "--- FindParse.cmake")
