MESSAGE(STATUS "+++ FindHipe.cmake")
SET (HIPE_DIR_ROOT ${PROJECT_SOURCE_DIR}/third/hipe)

set(HIPE_INCLUDE_DIRS ${PROJECT_SOURCE_DIR}/third/hipe/include)



if(NOT EXISTS ${HIPE_INCLUDE_DIRS})
	EXECUTE_PROCESS(COMMAND mkdir -p ${HIPE_INCLUDE_DIRS}
									WORKING_DIRECTORY ${HIPE_DIR_ROOT})
endif()


#构建JSON函数
FUNCTION (CLONE_HIPE)

	MESSAGE(STATUS "+++ CLONE_HIPE")

	#Setp 1 克隆hipe工程
	EXECUTE_PROCESS ( COMMAND git clone https://github.com/CodingHanYa/Hipe ${HIPE_INCLUDE_DIRS}
										WORKING_DIRECTORY ${HIPE_DIR_ROOT})

	MESSAGE(STATUS "--- BUILD_JSONCPP")

ENDFUNCTION ()

if(NOT EXISTS ${HIPE_INCLUDE_DIRS}/hipe.h)
	CLONE_HIPE()
endif()

MESSAGE("HIPE_INCLUDE_DIRS" ${HIPE_INCLUDE_DIRS})
set (HIPE_FOUND TRUE)

MESSAGE(STATUS "--- FindHipe.cmake")
